### ISSUE TITLE
sidekiq method no loger out

### ISSUE THREAD

**Issue by jaylee-404** [igorkasyanchuk/benchmark_methods#3]
when use sidekiq
def perform()
  .........
end
no time log print out

**Comment by igorkasyanchuk** [comment]
https://github.com/igorkasyanchuk/benchmark_methods/blob/master/lib/benchmark_methods.rb#L16
as you can see logs exists.
maybe it's in development.log or production.log? or sidekiq.log?

**Comment by Marshall-slim-jlee** [comment]
thanks, i mean sidekiq.log
